Feat/US-202 matomo analytics tracking urls
SocialGouv/pass_emploi_app pull request #135
Opened 2022-01-04 16:31 UTC by lela-oc-to

2022-01-04 16:39 UTC, BonnetM requested changes

2022-01-04 16:39 UTC, BonnetM commented on lib/pages/boite_a_outils_page.dart
> +class BoiteAOutilsPage extends TraceableStatelessWidget {
Ouh bien vu ! 👀

2022-01-04 16:39 UTC, BonnetM commented on lib/widgets/user_action_details_bottom_sheet.dart
> +    MatomoTracker.trackEvent(AnalyticsScreenNames.updateUserAction, 'Click');
Est-ce que ça serait pas plutôt `trackScreenWithName` ? 

Dans la doc ils disent : 

> 
> To track views simply replace StatelessWidget by TraceableStatelessWidget, StatefulWidget by TraceableStatefulWidget and finally InheritedWidget by TraceableInheritedWidget.
> 
> You can also optionally call directly trackScreen or trackScreenWithName to track a view.

Et c'est bien ce qui est appelé dans l'implem des `TraceableXXXWidget` Du coup on serait iso avec le reste du tracking déjà fait

2022-01-04 16:42 UTC, lela-oc-to commented on lib/widgets/user_action_details_bottom_sheet.dart
> +    MatomoTracker.trackEvent(AnalyticsScreenNames.updateUserAction, 'Click');
Bien vu, merci !

2022-01-04 17:08 UTC, adgeg approved these changes

2022-01-05 09:23 UTC, RemiDormoy approved these changes

2022-01-05 10:25 UTC, merged