Feat/us 226 actions and appointments are not available for Pole Emploi youth
SocialGouv/pass_emploi_app pull request #152
Opened 2022-01-14 15:21 UTC by lela-oc-to

📝.  Le ticket sur [https://trello.com/c/brvWBMlq/226-us-226-les-jeunes-pe-sont-inform%C3%A9s-que-les-actions-et-rdv-ne-sont-pas-disponibles](TRELLO)

⛔️  Le ticket concerné coté back n'est pas mergé, pas possible de tester  la co via Pole emploi

🖼.  J'ai profité ce ticket pour fixer le login page sur les petits devices

2022-01-14 16:38 UTC, BonnetM requested changes
RC surtout pour le check du login dans la page, des ptites remarques sur la gestion des petits écrans :)

2022-01-14 16:38 UTC, BonnetM commented on lib/pages/login_page.dart
> +                flex: _isLittleScreen(context) ? 3 : 2,
C'était déjà comme ça avant, mais j'ai l'impression qu'on n'a pas besoin de mettre un Expanded ici en fait. De ce que je comprends, on aimerait que ce bloc prenne toute la place dont il a besoin, et que le logo et l'espace en dessous se dimensionnent suivant l'espace restant. Et c'est ce qui se passerait si on enlève le `Expandend` :)

2022-01-14 16:38 UTC, BonnetM commented on lib/pages/login_page.dart
> +      margin: _isLittleScreen(context) ? EdgeInsets.only(left: 0, right: 0) : EdgeInsets.only(left: 16, right: 16),
J'suis pas super à l'aise à jouer avec ce genre de `_isLittleScreen`, je suis par exemple tombé sur un device qui est pile au dessus de la limite, qui a donc un overflow. 

J'ai l'impression qu'en jouant avec les flexible on pourrait s'en sortir sans, non ?

Et est-ce qu'ici on ne pourrait pas juste avoir un bouton avec du texte sur 2 lignes ?

2022-01-14 16:38 UTC, BonnetM commented on lib/widgets/unavailable_content.dart
> +    final bool littleScreen = _isLittleScreen(context);
Voir mon com sur la LoginPage, ça serait cool de voir si on peut s'en passer 🤔

2022-01-14 16:38 UTC, BonnetM commented on lib/widgets/unavailable_content.dart
> +        children: [
Est-ce qu'ici on ne pourrait pas utiliser des flexibles sur l'image et l'espace en haut et en bas pour laisser un max d'espace au texte et au bouton ?

2022-01-18 15:37 UTC, lela-oc-to commented on lib/pages/rendezvous_list_page.dart
> +          : _body(context, viewModel)),
Done ✅

2022-01-18 15:37 UTC, lela-oc-to commented on lib/pages/login_page.dart
> +                flex: _isLittleScreen(context) ? 3 : 2,
Done ✅

2022-01-18 15:37 UTC, lela-oc-to commented on lib/pages/login_page.dart
> +      margin: _isLittleScreen(context) ? EdgeInsets.only(left: 0, right: 0) : EdgeInsets.only(left: 16, right: 16),
Done ✅

2022-01-18 15:37 UTC, lela-oc-to commented on lib/widgets/unavailable_content.dart
> +    final bool littleScreen = _isLittleScreen(context);
Done ✅

2022-01-18 15:38 UTC, lela-oc-to commented on lib/widgets/unavailable_content.dart
> +        children: [
Done ✅

2022-01-18 16:12 UTC, lela-oc-to commented on lib/pages/rendezvous_list_page.dart
> +  bool _isPoleEmploiLogin(BuildContext context) =>
Done ✅

2022-01-18 16:42 UTC, merged