Feat/ US-281 K can save a job alternance immersion search
SocialGouv/pass_emploi_app pull request #192
Opened 2022-02-10 14:59 UTC by lela-oc-to

YEY FINALLY 🥳
[https://trello.com/c/S2xah2Nm/281-us-281-k-peut-enregistrer-une-recherche-doffre-demploi-dalternance-et-dimmersion](TRELLO)

2022-02-10 16:11 UTC, adgeg commented on lib/analytics/analytics_constants.dart
> +  static const emploiCreateAlert= "/saved_search/emploi/create";
Juste pour m'assurer avec vous que c'est bien "/saved_search" et pas "saved_search" (sans "/")

2022-02-10 16:16 UTC, adgeg commented on lib/pages/immersion_list_page.dart
> +      // ).then((value) => _onCreateUserActionDismissed(viewModel)),
BSR : à supprimer

2022-02-10 16:29 UTC, adgeg commented on lib/widgets/snack_bar/show_snack_bar.dart
> +showSuccessfulSnackBar(BuildContext context, String label) {
BSR Typer en `void`

2022-02-10 16:29 UTC, RemiDormoy commented on lib/analytics/analytics_constants.dart
> +  static const emploiCreateAlert= "/saved_search/emploi/create";
À priori oui, on checkera avec les PO si c'est bien ce qu'ils veulent

2022-02-10 16:30 UTC, adgeg commented on lib/widgets/snack_bar/show_snack_bar.dart
> +showSnackBarError(BuildContext context, String label) {
BSR Typer en `void`

2022-02-10 17:41 UTC, BonnetM requested changes
GG pour le boulot 💪 Je pense qu'on aurait clairement dû découper ça en plusieurs tickets ... Je crois en avoir fait 3 pour les favoris immersions, qui ressemble pas mal 😞 

C'est dommage d'avoir bougé autant de fichiers sur cette PR. Je suis d'accord qu'il fallait ranger le dossier widgets, mais ça fait énormément de bruit ici ... 

Et petit retour fonctionnel : lorsque je valide, j'ai la snackbar d'erreur qui apparaît tout le temps, puis remplacée par celle de succès, c'est un peu bizarre :)

2022-02-10 17:41 UTC, BonnetM commented on lib/pages/immersion_list_page.dart
> +        StoreProvider.of<AppState>(context).dispatch(InitializeSaveSearchAction<ImmersionSavedSearch>());
En fait, je viens de voir qu'il y a déjà un dispatch d'action dans le `onInit` de la bottom sheet, mais une `CreateSavedSearchAction`. Et on voit dans le `InitializeSavedSearchMiddleware` que lorsqu'on reçoit une `InitializeSaveSearchAction`, on redispatche une `CreateSavedSearchAction` ... J'ai l'impression qu'il y a un doublon quelque part 🤔

2022-02-10 17:41 UTC, BonnetM commented on lib/pages/immersion_list_page.dart
> +        StoreProvider.of<AppState>(context).dispatch(InitializeSaveSearchAction<ImmersionSavedSearch>());
J'ai l'impression qu'on pourrait enlever le dispatch ici, et le mettre à la place du dispatch de la `CreateSavedSearchAction` dans la bottom sheet, non ?

2022-02-10 17:41 UTC, BonnetM commented on lib/pages/immersion_list_page.dart
> +        StoreProvider.of<AppState>(context).dispatch(InitializeSaveSearchAction<ImmersionSavedSearch>());
(oui je parle tout seul)

2022-02-10 17:41 UTC, BonnetM commented on lib/widgets/bottom_sheets/saved_search_bottom_sheet.dart
> +      onInit: (store) => store.dispatch(CreateSavedSearchAction<SAVED_SEARCH_MODEL>),
En fait, j'ai l'impression que cette ligne ne fait rien du tout : on dispatche le `CreateSavedSearchAction` sans valeur, donc j'ai l'impression qu'on dispatche une fonction et pas une valeur.
Donc à remplacer par un `store.dispatch(InitializeSaveSearchAction<SAVED_SEARCH_MODEL>())` ?

2022-02-10 17:41 UTC, BonnetM commented on lib/redux/middlewares/initialize_saved_search_middleware.dart
> +      final OffreEmploiSavedSearch search = OffreEmploiSearchExtractor().getSearchFilters(store);
Un peu bizarre qu'un middleware tape sur une classe qui est dans le fichier du view model

2022-02-10 17:41 UTC, BonnetM commented on lib/presentation/saved_search_view_model.dart
> +    final eLocation = state.location;
Des prefixes `e` en trop ?

2022-02-10 17:41 UTC, BonnetM commented on lib/presentation/saved_search_view_model.dart
> +      searchModel: search.getSearchFilters(store),
Pourquoi on refait un `search.getSearchFilters` ici, alors qu'on l'a fait dans le middleware ? 
Il ne faudrait pas plutôt récupérer le `savedSearch` qui est dans l'état `SavedSearchInitialized` ?

2022-02-10 17:41 UTC, BonnetM commented on lib/redux/middlewares/saved_search_middleware.dart
> +  dynamic _extractSearch(SavedSearchState<Equatable> emploiSavedSearchState) {
On pourrait être plus précis dans le typage et mettre `T?`, non ?

2022-02-10 17:41 UTC, BonnetM commented on lib/redux/middlewares/saved_search_middleware.dart
> +      savedSearch,
Voir mon com juste en dessous, mais en typant, on se rend compte qu'on passe un champ nullable à un argument qui ne l'est pas, il faudrait faire un check avant

2022-02-10 17:41 UTC, BonnetM commented on lib/widgets/bottom_sheets/offre_emploi_saved_search_bottom_sheet.dart
> +class OffreEmploiSavedSearchBottomSheet extends AbstractSavedSearchBottomSheet<OffreEmploiSavedSearch> {
Le fichier pourrait être reformaté

2022-02-10 17:41 UTC, BonnetM commented on lib/widgets/bottom_sheets/saved_search_bottom_sheet.dart
> +  final SavedSearchState<SAVED_SEARCH_MODEL> Function(Store<AppState> store) selectState;
J'ai l'impression qu'il n'est pas utilisé pour l'instant 🤔 
Mais si on veut aller chercher le `savedSearch` qui est dans l'état `SavedSearchInitialized` dans le view model (ce que je proposais dans mon autre com), j'ai l'impression qu'il faudrait en effet faire un truc dans le genre

2022-02-10 17:41 UTC, BonnetM commented on lib/widgets/bottom_sheets/offre_emploi_bottom_sheet_form.dart
> +    List<TagInfo> _tags = widget.onlyAlternance
Ca fait pas mal de logique dans la vue, faudrait pas le mettre dans le view model plutôt ?

2022-02-10 17:41 UTC, BonnetM commented on test/feature/saved_search/immersion_saved_search_test.dart
> +main() {
Il manque des tests qui partent d'un dispatch de `InitializeSaveSearchAction`, je pense que ça aiderait pour mettre plus au clair ce qui se passe au lancement des bottom sheets

2022-02-10 17:41 UTC, BonnetM commented on lib/models/saved_search/immersion_saved_search.dart
> +class ImmersionSavedSearch extends Equatable {
Tant pis, mais on s'était dit qu'on utilisait plutôt du français pour les objets métiers

2022-02-10 17:41 UTC, BonnetM commented on test/repositories/savedSearch/immersion_saved_search_repository_test.dart
> +import 'package:flutter_test/flutter_test.dart';
Rien à voir avec cette ligne, mais le dossier de ce fichier devrait être `saved_search` et pas `savedSearch`

2022-02-10 17:41 UTC, BonnetM commented on test/repositories/savedSearch/immersion_saved_search_repository_test.dart
> +main() {
Très lisibles les tests avec les méthodes privées, noice 👌

2022-02-10 17:41 UTC, BonnetM commented on lib/ui/drawables.dart
> +  static String icInfoBlue = _assets + "ic_info_blue" + _svg;
Je sais pas si ça marcherait ici, mais pour info on peut colorier les vectors lorqu'on les affiche , genre `SvgPicture.asset(Drawables.icInfo color: AppColors.primary)`

2022-02-10 17:41 UTC, BonnetM commented on pubspec.lock
> +    version: "1.1.0"
J'ai un doute, mais normal que le `pubspec.lock` bouge alors que le `pubspec.yaml` n'a pas bougé ? 🤔

2022-02-11 11:04 UTC, RemiDormoy commented on lib/pages/immersion_list_page.dart
> +        StoreProvider.of<AppState>(context).dispatch(InitializeSaveSearchAction<ImmersionSavedSearch>());
Bien vu

2022-02-11 13:03 UTC, RemiDormoy commented on pubspec.lock
> +    version: "1.1.0"
Aucune idée

2022-02-11 13:08 UTC, RemiDormoy commented on lib/redux/middlewares/initialize_saved_search_middleware.dart
> +      final OffreEmploiSavedSearch search = OffreEmploiSearchExtractor().getSearchFilters(store);
Je les ai déplacé dans un fichier à part du coup les extractors

2022-02-11 13:19 UTC, RemiDormoy commented on lib/models/saved_search/immersion_saved_search.dart
> +class ImmersionSavedSearch extends Equatable {
Lana a pas voulu :-(

2022-02-11 14:24 UTC, RemiDormoy commented on lib/widgets/bottom_sheets/saved_search_bottom_sheet.dart
> +  final SavedSearchState<SAVED_SEARCH_MODEL> Function(Store<AppState> store) selectState;
Je l'ai viré du coup

2022-02-11 14:59 UTC, BonnetM approved these changes

2022-02-11 15:21 UTC, merged