Feat/us 378 service civique search
SocialGouv/pass_emploi_app pull request #219
Opened 2022-02-23 16:36 UTC by lela-oc-to

[TRELLO](https://trello.com/c/Hb8klCHN/378-k-peut-voir-les-crit%C3%A8res-de-recherche-service-civique)

DONE:
✅. UI de page de la recherche service civique
✅  Middleware & Actions
✅. Repo
✅. Test de repo

TODO:
◻️ Reducer
◻️ States
◻️ Feat test

2022-02-23 17:11 UTC, BonnetM approved these changes

2022-02-23 17:11 UTC, BonnetM commented on lib/pages/service_civique_search_page.dart
> +      converter: (store) => ServiceCiviqueViewModel.create(store),
on peut rajouter un `distinct: true` ?

2022-02-23 17:11 UTC, BonnetM commented on lib/redux/middlewares/search_service_civique_middleware.dart
> +      if (loginState.isSuccess()) {
Est-ce qu'on a vraiment besoin de ce check si on fait un  `getResultOrThrow` après ? 🤔

2022-02-23 17:11 UTC, BonnetM commented on lib/repositories/service_civique_repository.dart
> +  static const PAGE_SIZE = 50;
On ne parle pas de pagination dans l'US, on en a vraiment besoin ?

2022-02-23 17:11 UTC, BonnetM commented on lib/repositories/service_civique_repository.dart
> +      {required String userId, required SearchServiceCiviqueRequest request}) async {
Formattage un peu chelou

2022-02-24 15:13 UTC, lela-oc-to commented on lib/pages/service_civique_search_page.dart
> +      converter: (store) => ServiceCiviqueViewModel.create(store),
Done ✅

2022-02-24 15:13 UTC, lela-oc-to commented on lib/repositories/service_civique_repository.dart
> +  static const PAGE_SIZE = 50;
API le demande, mais c'est pas précisé dans l'US t'as raison

2022-02-24 15:13 UTC, lela-oc-to commented on lib/repositories/service_civique_repository.dart
> +      {required String userId, required SearchServiceCiviqueRequest request}) async {
Done ✅

2022-02-28 09:59 UTC, RemiDormoy commented on lib/redux/middlewares/search_service_civique_middleware.dart
> +      if (loginState.isSuccess()) {
Oui on en a besoin. Ça évite de thrower une erreur alors qu'on voudrait juste ne pas exécuter ce code non ?

2022-02-28 14:10 UTC, BonnetM requested changes

2022-02-28 14:10 UTC, BonnetM commented on lib/features/service_civique/search/service_civique_search_result_state.dart
> +  List<Object?> get props => [];
On pourrait mettre ça dans la classe abstraite pour ne l'overrider que dans le `ServiceCiviqueSearchResultDataState` (comme ce qui est fait pour le `ChatState` par exemple)

2022-02-28 14:10 UTC, BonnetM commented on lib/features/service_civique/search/search_service_civique_actions.dart
> +class ServiceCiviqueFailureAction extends ServiceCiviqueAction {}
Il manque pas la notion de "search" dans le nom ? `ServiceCiviqueSearchFailureAction` plutôt ?

2022-02-28 14:10 UTC, BonnetM commented on lib/features/service_civique/search/search_service_civique_actions.dart
> +class ServiceCiviqueSuccessAction extends ServiceCiviqueAction {
Idem ici, `ServiceCiviqueSearchSuccessAction` plutôt ?

2022-02-28 14:10 UTC, BonnetM commented on lib/features/service_civique/search/service_civique_reducer.dart
> +ServiceCiviqueSearchResultState serviceCiviqueReducer(AppState current, dynamic action) {
J'aurais plutôt typé le `current` en `ServiceCiviqueSearchResultState`, comme ça ce reducer ne s'occupe vraiment que de sous-état. Je m'étais posé la question de lui passer tout l'app state, mais a priori on n'en a pas besoin.

2022-02-28 14:24 UTC, BonnetM approved these changes

2022-02-28 14:26 UTC, merged