feat(2064): home recherche cards
SocialGouv/pass_emploi_app pull request #731
Opened 2023-11-22 15:58 UTC by Alwein

2023-11-23 07:29 UTC, adgeg commented on lib/pages/recherche/recherche_home_page.dart
> +import 'package:pass_emploi_app/widgets/cards/base_cards/widgets/card_body.dart';
Je te mets 3 retours UI ici pour que tu les prennes en compte : 2 sont d'avant, 1 de cette PR.

2023-11-23 07:31 UTC, adgeg commented on lib/pages/recherche/recherche_home_page.dart
> +import 'package:pass_emploi_app/widgets/cards/base_cards/widgets/card_body.dart';
<img width="309" alt="Capture d’écran 2023-11-23 à 08 26 04" src="https://github.com/SocialGouv/pass_emploi_app/assets/1272882/cf26b536-e741-4e34-8c5f-7c4870be374d">

1- Si tu peux mettre pour les actions le même formatteur de date que pour les démarches que ça tienne sur une ligne.
2 - Si tu peux éviter le gros trou blranc quand l'action n'a pas de description.

2023-11-23 07:41 UTC, adgeg requested changes

2023-11-23 07:41 UTC, adgeg commented on lib/pages/recherche/recherche_home_page.dart
> +import 'package:pass_emploi_app/widgets/cards/base_cards/widgets/card_body.dart';
<img width="332" alt="Capture d’écran 2023-11-23 à 08 27 14" src="https://github.com/SocialGouv/pass_emploi_app/assets/1272882/e0efaa71-b458-4e74-93ab-ae1729a2b93d">

3- Ca rend chelou le non alignement du coeur avec le titre :( On peut rien faire pour ça ?

2023-11-23 07:41 UTC, adgeg commented on lib/pages/recherche/recherche_home_page.dart
> +import 'package:pass_emploi_app/widgets/cards/base_cards/widgets/card_body.dart';
<img width="338" alt="Capture d’écran 2023-11-23 à 08 32 30" src="https://github.com/SocialGouv/pass_emploi_app/assets/1272882/925c01dc-4fba-4dd2-a111-4bec6f9d2856">

4- Et un que je n'avais pas vu sur l'autre PR (check les favoris du mode démo)

2023-11-23 07:41 UTC, adgeg commented on lib/widgets/cards/data_card.dart
> +    this.date,
BGSR : tu peux soit le mettre required soit le descendre après les required ?

2023-11-23 07:41 UTC, adgeg commented on lib/widgets/cards/data_card.dart
> +        if (lieu != null && lieu!.isNotEmpty) CardComplement.place(text: lieu!),
Une fois ma PR montée de version de Dart mergée et ta branche rebase, plus besoin des "!" après les null check ;) (4 `!` en moins)

2023-11-23 07:41 UTC, adgeg commented on lib/widgets/cards/data_card.dart
> +        if (category != null && category!.isNotEmpty) CardTag.secondary(text: category!),
same here

2023-11-23 07:41 UTC, adgeg commented on lib/widgets/cards/data_card.dart
> +      iconButton: FavoriHeart<T>(
A CORRIGER: Pourquoi tu as enlevé le `if (id != null && from != null)` ?

2023-11-24 09:44 UTC, Alwein commented on lib/pages/recherche/recherche_home_page.dart
> +import 'package:pass_emploi_app/widgets/cards/base_cards/widgets/card_body.dart';
Pour aligner l'iconButton j'ai fait un hack avec une stack

2023-11-24 12:43 UTC, merged